// lib/main.dart
import 'dart:async';

import 'package:app_links/app_links.dart';
import 'package:flutter/foundation.dart' show kIsWeb, debugPrint;
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'supabase_options.dart';
import 'screens/onboarding_screen.dart';
import 'screens/home_shell.dart';
import 'screens/item_landing_screen.dart';
import 'screens/reset_password_screen.dart';
import 'screens/tag_landing_screen.dart';
import 'services/ad_service.dart';
import 'state/app_state.dart';
import 'theme/app_theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Supabase.initialize(
    url: SupabaseOptions.supabaseUrl,
    anonKey: SupabaseOptions.supabaseAnonKey,
  );
  // Ad consent (UMP) + Mobile Ads SDK init. Runs in the background so a
  // slow consent-info fetch never blocks the app from showing its first
  // screen — the banner just appears once this resolves.
  unawaited(AdService.initialize());
  runApp(
    ChangeNotifierProvider(
      create: (_) => AppState(),
      child: const LostFoundApp(),
    ),
  );
}

/// Builds the screen for a `tag/<code>`, `item/<id>`, or default route,
/// shared between the web URL-bar route (onGenerateRoute) and native
/// `foundify://` deep links (handled in _LostFoundAppState below) — both
/// forms of link land on the same pages.
Widget _screenForUri(Uri uri) {
  if (uri.pathSegments.length >= 2 && uri.pathSegments[0] == 'tag') {
    return TagLandingScreen(code: uri.pathSegments[1]);
  }
  if (uri.pathSegments.length >= 2 && uri.pathSegments[0] == 'item') {
    return ItemLandingScreen(itemId: uri.pathSegments[1]);
  }
  final user = Supabase.instance.client.auth.currentUser;
  return user == null ? const OnboardingScreen() : const HomeShell();
}

class LostFoundApp extends StatefulWidget {
  const LostFoundApp({super.key});

  @override
  State<LostFoundApp> createState() => _LostFoundAppState();
}

class _LostFoundAppState extends State<LostFoundApp> {
  final _navigatorKey = GlobalKey<NavigatorState>();
  StreamSubscription<Uri>? _linkSub;
  StreamSubscription<AuthState>? _authSub;

  @override
  void initState() {
    super.initState();
    if (!kIsWeb) _initDeepLinks();

    // Following a "reset your password" email link signs the user into a
    // temporary recovery session and Supabase fires this specific event —
    // that's the app's cue to show the actual "set a new password" form,
    // instead of just landing back on Home with nothing to do about it.
    _authSub = Supabase.instance.client.auth.onAuthStateChange.listen((data) {
      if (data.event == AuthChangeEvent.passwordRecovery) {
        _navigatorKey.currentState?.push(
          MaterialPageRoute(builder: (_) => const ResetPasswordScreen()),
        );
      }
    });
  }

  /// Native `foundify://open/tag/<code>` links — generated by
  /// lib/screens/item_tags_screen.dart#tagUrl — and the "Open in Foundify
  /// App" button on the shared item preview page (see
  /// lib/widgets/item_card.dart#itemShareLink) route into the app directly
  /// via this listener.
  Future<void> _initDeepLinks() async {
    final appLinks = AppLinks();
    try {
      final initial = await appLinks.getInitialLink();
      if (initial != null) _pushForUri(initial);
    } catch (e) {
      debugPrint('Failed to read initial deep link: $e');
    }
    _linkSub = appLinks.uriLinkStream.listen(
      _pushForUri,
      onError: (e) => debugPrint('Deep link stream error: $e'),
    );
  }

  void _pushForUri(Uri uri) {
    final navigator = _navigatorKey.currentState;
    if (navigator == null) return;
    navigator.push(MaterialPageRoute(builder: (_) => _screenForUri(uri)));
  }

  @override
  void dispose() {
    _linkSub?.cancel();
    _authSub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: _navigatorKey,
      debugShowCheckedModeBanner: false,
      title: 'Foundify',
      theme: AppTheme.light(),
      onGenerateRoute: (settings) {
        final uri = Uri.parse(settings.name ?? '/');
        return MaterialPageRoute(builder: (_) => _screenForUri(uri));
      },
    );
  }
}
