// lib/screens/item_landing_screen.dart
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import '../models/item.dart';
import '../services/supabase_service.dart';
import '../theme/app_theme.dart';
import '../widgets/item_card.dart' show timeAgo, thumbColorFor;
import 'home_shell.dart';
import 'onboarding_screen.dart';

/// Public "shared item" landing page — reached via the link generated by the
/// Share button on an item (see item_detail_screen.dart / feed_post_card.dart).
/// No login required: fetches the live item straight from Supabase, so
/// whoever opens the link always sees current, real data — not a static
/// snapshot of what was true when it was shared.
class ItemLandingScreen extends StatefulWidget {
  final String itemId;
  const ItemLandingScreen({super.key, required this.itemId});

  @override
  State<ItemLandingScreen> createState() => _ItemLandingScreenState();
}

class _ItemLandingScreenState extends State<ItemLandingScreen> {
  Item? item;
  bool loading = true;
  bool notFound = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    try {
      // No `profiles` join: profiles RLS is owner-only (see
      // supabase/migrations/0009_secure_profiles_contact.sql) and this page
      // is reached with no login at all. The item row already snapshots the
      // poster's username/avatar_url at creation time (createItem), which
      // Item.fromMap falls back to.
      final res = await SupabaseService.supabase
          .from('items')
          .select('*')
          .eq('id', widget.itemId)
          .isFilter('deleted_at', null)
          .maybeSingle();
      if (res == null) {
        if (mounted) setState(() => notFound = true);
        return;
      }
      final map = Map<String, dynamic>.from(res as Map);
      await SupabaseService.attachLivePosterInfo([map]);
      if (mounted) setState(() => item = Item.fromMap(map));
    } catch (e) {
      if (mounted) setState(() => notFound = true);
    } finally {
      if (mounted) setState(() => loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 480),
            child: loading
                ? const Center(child: CircularProgressIndicator())
                : notFound || item == null
                ? _buildNotFound(context)
                : _buildItem(context, item!),
          ),
        ),
      ),
    );
  }

  Widget _buildNotFound(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(24),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          _brandHeader(context),
          Icon(Icons.search_off, size: 56, color: Colors.grey.shade300),
          const SizedBox(height: 16),
          const Text(
            'This report is no longer available',
            style: TextStyle(fontWeight: FontWeight.w800, fontSize: 18),
          ),
          const SizedBox(height: 8),
          const Text(
            "It may have been resolved and removed, or the link is incorrect.",
            textAlign: TextAlign.center,
            style: TextStyle(color: AppColors.neutralGrey),
          ),
        ],
      ),
    );
  }

  Widget _buildItem(BuildContext context, Item item) {
    final images = (item.imageUrls != null && item.imageUrls!.isNotEmpty)
        ? item.imageUrls!
        : (item.imageUrl != null && item.imageUrl!.isNotEmpty
              ? [item.imageUrl!]
              : <String>[]);
    final status = item.returned ? 'Resolved' : 'Open';

    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _brandHeader(context),
          ClipRRect(
            borderRadius: BorderRadius.circular(16),
            child: AspectRatio(
              aspectRatio: 1,
              child: images.isEmpty
                  ? Container(
                      color: thumbColorFor(item.id),
                      child: Center(
                        child: Icon(
                          categoryIcon(item.category ?? ''),
                          size: 64,
                          color: AppColors.primary500,
                        ),
                      ),
                    )
                  : CachedNetworkImage(
                      imageUrl: images.first,
                      fit: BoxFit.cover,
                      memCacheWidth: 960,
                    ),
            ),
          ),
          const SizedBox(height: 16),
          Wrap(
            spacing: 8,
            children: [
              if ((item.category ?? '').isNotEmpty)
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 6,
                  ),
                  decoration: BoxDecoration(
                    color: AppColors.accent100,
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Text(
                    item.category!,
                    style: const TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              StatusBadge(status: status),
            ],
          ),
          const SizedBox(height: 12),
          Text(item.title, style: Theme.of(context).textTheme.headlineSmall),
          const SizedBox(height: 4),
          Text(
            '${item.status == 'lost' ? 'Lost' : 'Found'} · ${item.locationLabel ?? 'Nearby'} · ${timeAgo(item.createdAt)}',
            style: const TextStyle(color: AppColors.neutralGrey),
          ),
          const SizedBox(height: 16),
          Text(
            item.description.isNotEmpty
                ? item.description
                : 'No description provided.',
            style: const TextStyle(fontSize: 15, height: 1.4),
          ),
          const SizedBox(height: 24),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppColors.primary50,
              borderRadius: BorderRadius.circular(14),
            ),
            child: Row(
              children: [
                const Icon(Icons.info_outline, color: AppColors.primary500),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    'Open the Foundify app and search for "${item.title}" to message the reporter.',
                    style: const TextStyle(fontSize: 13),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _brandHeader(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Column(
        children: [
          FoundifyLogo(
            size: 48,
            onTap: () => Navigator.pushAndRemoveUntil(
              context,
              MaterialPageRoute(
                builder: (_) => SupabaseService.currentUser() == null
                    ? const OnboardingScreen()
                    : const HomeShell(),
              ),
              (r) => false,
            ),
          ),
          const SizedBox(height: 12),
          Text('Foundify', style: Theme.of(context).textTheme.titleLarge),
        ],
      ),
    );
  }
}
